client:
  build: .
  command: client
  environment:
    CLIENT_NAME: bob
    RUNTIME_INSTALL: disk-checks
    RABBITMQ_HOST:
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - conf.d/:/etc/sensu/conf.d/