api:
  build: .
  restart: always
  command: api
  links:
    - rabbitmq
    - redis
  environment:
    RUNTIME_INSTALL: disk-checks
    LOG_LEVEL: DEBUG
  volumes:
    - conf.d/:/etc/sensu/conf.d/
server:
  build: .
  restart: always
  command: server
  links:
    - rabbitmq
    - redis
    - api
  environment:
    RUNTIME_INSTALL: disk-checks
    LOG_LEVEL: DEBUG
  volumes:
    - conf.d/:/etc/sensu/conf.d/
uchiwa:
  image: uchiwa/uchiwa
  restart: always
  links:
    - api:sensu
  ports:
    - '80:3000'
  volumes:
    - ./uchiwa/:/config
rabbitmq:
  image: rabbitmq:3.5-management
  restart: always
  ports:
    - '5672:5672'
redis:
  image: redis
  restart: always
