api:
  build: .
  restart: always
  command: api
  links:
    - rabbitmq
    - redis
  env_file: .env
  volumes:
    - conf.d/:/etc/sensu/conf.d/

server:
  build: .
  restart: always
  command: server
  links:
    - rabbitmq
    - redis
    - api
  env_file: .env
  volumes:
    - conf.d/:/etc/sensu/conf.d/

uchiwa:
  image: uchiwa/uchiwa
  restart: always
  links:
    - api:sensu
  volumes:
    - ./uchiwa/:/config

nginx:
  build: nginx/.
  links:
    - uchiwa
  ports:
    - "80:80"

rabbitmq:
  image: rabbitmq:3.5-management
  restart: always
  ports:
    - '5672:5672'
redis:
  image: redis
  restart: always
